{"uuid": "8931049c-050d-4938-adbf-1e093180ac43", "children": ["d626d5af-4313-4aa3-8c30-067158f36cde", "56f71cb7-7636-46e9-9fe6-7611fc8e93f4", "9b488598-3920-4cc1-be3e-d0722e6b892f", "e208cc7e-2965-4cad-8f10-187e00ab483a"], "befores": [{"name": "get_token", "status": "broken", "statusDetails": {"message": "AttributeError: 'Logger' object has no attribute 'logger'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tim/Desktop/test_pro/pyframe/testcases/conftest.py\", line 33, in get_token\n    log.logger.info(\"Authorization:Bearer \"+token[0])\n    ^^^^^^^^^^\n"}, "start": 1716088783289, "stop": 1716088783745}], "start": 1716088783289, "stop": 1716088783839}