{"uuid": "2d394183-ac07-4649-ab2c-8f5021a8fc35", "children": ["48415371-fa83-4580-8b4e-5a39e280c471", "e403344f-1080-4ed1-8423-078de0a88745", "567c01dd-30cf-4b64-b6c6-7279a8b1d9c2", "c6096319-5228-49a1-b0eb-a574879e2b62"], "befores": [{"name": "get_token", "status": "broken", "statusDetails": {"message": "AttributeError: 'Logger' object has no attribute 'logger'\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/_pytest/fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n                     ^^^^^^^^^^^^^^^^^^^^^\n  File \"/Users/tim/Desktop/test_pro/pyframe/testcases/conftest.py\", line 33, in get_token\n    log.logger.info(\"Authorization:Bearer \"+token[0])\n    ^^^^^^^^^^\n"}, "start": 1716088912507, "stop": 1716088912838}], "start": 1716088912507, "stop": 1716088912927}